### ISSUE TITLE
Auto-completion for arrays does not works

### ISSUE THREAD

**Issue by gavr123456789** [benwaffle/vala-language-server#107]
**Describe the bug**
Auto-completion for arrays does not works

**Software**
OS and version (e.g. Ubuntu 20.04): arch
Code editor (e.g. VSCode): VSCode
Vala Language Server (e.g. git commit, or PPA/AUR version): workflow-improvements branch
Vala version (valac --version): 0.48.4

**To Reproduce**
```vala
    string[] splitted2 = "asd:dsa".split(":");
    splitted2.
```
![изображение](https://user-images.githubusercontent.com/30507409/80455877-3f825700-8935-11ea-9225-635aa86cc74a.png)

**Comment by Prince781** [comment]
It looks like arrays required some special handling.
