### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by benwaffle** [benwaffle/vala-language-server#11]

**Comment by minkir014** [comment]
What do you mean with error handling? Do you mean code fixes?

**Comment by minkir014** [comment]
@benwaffle Are you here?

**Comment by benwaffle** [comment]
I think I just meant improving error handling

**Comment by Prince781** [comment]
I think we've largely addressed this issue. By making warnings fatal, we've forced ourselves to capture and recover from errors throughout the code.
