### ISSUE TITLE
Can't install on elementary OS

### ISSUE THREAD

**Issue by AnderRasoVazquez** [benwaffle/vala-language-server#116]
**Describe the bug**
It needs a greater version of libvala that we have (0.40).

Error message in spanish:
`vala-language-server : Depende: libvala-0.48-0 (>= 0.47.3) pero no es instalable`

**Software**
elementary OS 5.1.4 Hera

**To Reproduce**
Try to install it following Readme.md instructions.

```
sudo add-apt-repository ppa:prince781/vala-language-server
sudo apt-get update
sudo apt-get install vala-language-server
```

**Comment by Prince781** [comment]
You need to install the Vala Next PPA: https://launchpad.net/~vala-team/+archive/ubuntu/next/+packages

```
sudo apt-add-repository ppa:vala-team/next
```

We should probably add this to the README.

**Comment by Prince781** [comment]
So, can I close this? I take it you've solved your problem?

**Comment by AnderRasoVazquez** [comment]
Yes.

**Comment by Prince781** [comment]
Glad to hear. Please don't hesitate to ask if you have new problems, but for questions please use the Gitter room.
