### ISSUE TITLE
meson.build:12:2: ERROR: Problem encountered: libvala needs to be 0.48 or above

### ISSUE THREAD

**Issue by Baloneo** [benwaffle/vala-language-server#119]
**Describe the bug**
meson.build:12:2: ERROR: Problem encountered: libvala needs to be 0.48 or above

**Software**
OS and version (e.g. Ubuntu 20.04): linux mint 19.3
Code editor (e.g. VSCode): VSCode
Vala Language Server (e.g. git commit, or PPA/AUR version): 
Vala version (`valac --version`): Vala 0.40.19

**To Reproduce**
Source code repo:

1. `sudo dpkg -i libvala-0.48-0_0.48.6-1_amd64.deb`
2. git clone this project
3. cd this project
4. `meson build`

ERROR:
```
The Meson build system
Version: 0.54.2
Source dir: /home/baloneo/下载/chrome-download/vala-language-server-master
Build dir: /home/baloneo/下载/chrome-download/vala-language-server-master/build
Build type: native build
Project name: vala-language-server
Project version: 0.48
C compiler for the host machine: cc (gcc 7.5.0 "cc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0")
C linker for the host machine: cc ld.bfd 2.30
Vala compiler for the host machine: valac (valac 0.40.19)
Host machine cpu family: x86_64
Host machine cpu: x86_64

meson.build:12:2: ERROR: Problem encountered: libvala needs to be 0.48 or above

A full log can be found at /home/baloneo/下载/chrome-download/vala-language-server-master/build/meson-logs/meson-log.txt

```

m

**Comment by Prince781** [comment]
VLS only works with Vala 0.48 and higher. You can install this version of Vala by adding the PPA `vala-team/next`

**Comment by Prince781** [comment]
See https://github.com/benwaffle/vala-language-server/issues/116#issuecomment-629562114

**Comment by Baloneo** [comment]
thank you
