### ISSUE TITLE
GNOME Builder plugin

### ISSUE THREAD

**Issue by Prince781** [benwaffle/vala-language-server#12]

**Comment by gavr123456789** [comment]
It alive, right?

**Comment by Prince781** [comment]
Unfortunately, Ben and I don't have the time to work on this project continuously. Work has been, at best, sporadic. You're welcome to contribute if you feel you're able to.

**Comment by gavr123456789** [comment]
I can't. I am a newcomer in Vala world. And it's just not very comfortable that the language has no language server since 2006 lel.

**Comment by benwaffle** [comment]
check out https://gitlab.gnome.org/esodan/gvls as well

**Comment by Prince781** [comment]
I guess we can start here: https://builder.readthedocs.io/en/latest/plugins/editor/

**Comment by benwaffle** [comment]
See the rust language server plugin as an example https://github.com/gnome/gnome-builder/blob/master/src/plugins/rls/rls_plugin.py

**Comment by Prince781** [comment]
In `gb-integration` I have a rudimentary plugin that spawns vls. strace shows that it's sending the right JSON-RPC commands to Builder, which doesn't seem to be acting on them. It's a little tricky trying to monitor the communication between the two processes since there's a lot of noise.

**Comment by Prince781** [comment]
It's almost there. Current issue is that you have to:

1. open vala project in GNOME Builder
2. kill vala-language-server

to get diagnostics to show up as you type.

**Comment by Prince781** [comment]
I've partially reverted 3f2cae0667d3a591e4b8b7eddefb986ecbeca7b2, which fixes the issue. I guess it's probably because of the environment variables I was using. Nevertheless, I'm keeping this change since it should prevent all surprises in the future.

**Comment by Prince781** [comment]
We could take a look at the gvls plugin now that it's been added to Builder.

**Comment by esodan** [comment]
Please do it. GVls need more tests and fixes for better diagnostics and completion. While there are some work left in Builder the features are there.

In Builder the most annoying issue is to detect the `--pkg` and other switches used at build time, so diagnostics can provide reliable messages and completion can also provide symbols from namespaces in use.

**Comment by Prince781** [comment]
I've tested with GNOME Builder and things are working now, at least for meson projects.
