### ISSUE TITLE
How to include local vapi file to the server search path?

### ISSUE THREAD

**Issue by aeldemery** [benwaffle/vala-language-server#126]
I have compiled vala from source with the newest gtk4 vapi. The server don't auto-complete the new symbols from the new installation, only from outdated system package installation file.
Is there a possibility to edit search paths for the server?

**Comment by Prince781** [comment]
I think that would depend on your build configuration, right?

**Comment by aeldemery** [comment]
> I think that would depend on your build configuration, right?

I use the normal meson `dependency ('gtk4')`
even tried to put the newest vapi in a local directory and used
`add_project_arguments(['--vapidir', vapi_dir], language: 'vala')`
but that didn't work.
in general is there a config file that allow one to tweak the internals of the server like for example search paths?

**Comment by Prince781** [comment]
Did you install this Vala into a location like `/usr/local`?

**Comment by aeldemery** [comment]
That's right. /usr/local is the installation place.

**Comment by Prince781** [comment]
And is Vala Language Server compiled and linked against the Vala in `/usr/local`?

**Comment by aeldemery** [comment]
Solved. I've rebuild the server against my new Vala installation and now all the new symbols are visible. Thanks :-)

**Comment by Prince781** [comment]
Yes. Remember that VLS is tightly coupled to the Vala library it was compiled with.
