### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by danielpinto8zz6** [benwaffle/vala-language-server#13]
we can use uncrustify to format code..

**Comment by danielpinto8zz6** [comment]
do you know this repo? https://github.com/davidmhewitt/vala-language-server
it has formatting

**Comment by benwaffle** [comment]
yep, i'm following it

**Comment by benwaffle** [comment]
@Prince781  can we copy this GPL3 code into our project? https://github.com/davidmhewitt/vala-language-server/blob/master/src/ValaFormatter.vala

**Comment by Prince781** [comment]
I chose GPL3 but then switched to LGPL 2.1 (what vala is) because some vala contributors on IRC mentioned the possibility of this work going into it. 

GPL3 states that programs that link to the code have to be GPL3. LGPL 2.1 doesn't require this.

**Comment by Prince781** [comment]
@benwaffle See this: https://github.com/davidmhewitt/vala-language-server/issues/2

**Comment by benwaffle** [comment]
but are we allowed to put a GPLv3 file in a LGPL 2.1 project, and leave it as GPLv3?

**Comment by Prince781** [comment]
According to [this](https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility) (see column 4, row 3), the whole project would have to become GPL3.

**Comment by danielpinto8zz6** [comment]
another one: https://gitlab.gnome.org/esodan/gvls
