### ISSUE TITLE
Rename folder builddir  to .build

### ISSUE THREAD

**Issue by taozuhong** [benwaffle/vala-language-server#131]
Vls: latest version
Vala: 0.48.6
VSCode: 1.45

found a new folder: builddir, it created by vls,
I think it should be .build, and add it into .gitignore;

**Comment by Prince781** [comment]
It's not created by VLS, it's created by the VSCode Meson plugin.

**Comment by taozuhong** [comment]
it exists while starting Vls + Vala vscode, I think one of them must be the creator.

**Comment by Prince781** [comment]
@taozuhong try uninstalling the Meson plugin for VSCode, deleting the builddir directory, and starting again.

**Comment by taozuhong** [comment]
OK, I'll try.
