### ISSUE TITLE
Ubuntu PPA: build packages for Focal and Eoan

### ISSUE THREAD

**Issue by EpsilonKu** [benwaffle/vala-language-server#134]
**Describe the bug**
In ppa:prince781/vala-language-server there is no installation for Ubuntu 18.10, 19.04, 19.10, 20.04.

**Comment by Prince781** [comment]
Are you on Ubuntu 20.04? I just added a package for it. You should be able to install VLS now.

**Comment by EpsilonKu** [comment]
Well, it works fine. Checked with Kubuntu 20.04 on Vim (coc.nvim).

**Comment by Prince781** [comment]
@EpsilonKu great to hear. I guess I can close this issue now?

**Comment by Prince781** [comment]
Just so you are aware, we are now dropping support for Ubuntu 18.10, 19.04, and 19.10 as they are now officially unsupported. Ubuntu 18.04 will be supported because it is a LTS release. Please upgrade to Ubuntu 20.04 or later.
