### ISSUE TITLE
Language server crashes repeatedly on WSL

### ISSUE THREAD

**Issue by aggalex** [benwaffle/vala-language-server#143]
**Describe the bug**
The server crashes on startup with an assertion failure:

    (process:489): vala-CRITICAL **: 10:15:19.230: vala_source_reference_construct: assertion '_file != NULL' failed

**Software**
OS and version (e.g. Ubuntu 20.04): Ubuntu 20.04 on WSL
Code editor (e.g. VSCode): VSCode
Vala Language Server (e.g. git commit, or PPA/AUR version): PPA
Vala version (`valac --version`): Vala 0.48.6

**To Reproduce**
1. Install Vala and VLS on Ubuntu 20.04 WSL
2. Run `code .` to open VSCode on WSL
3. Install the Vala extension and reload
4. VLS will start trying to find the meson building system, the GIRs, etc, and will in the end halt with that error.
5. Eventually, VSCode will stop restarting VLS, citing that it crashed 5 times in the last 3 minutes.

**Comment by Prince781** [comment]
Can you send a full log? It would help.

**Comment by Prince781** [comment]
Just curious, does [`wip/win32-process-creation-workaround`](https://github.com/benwaffle/vala-language-server/tree/wip/win32-process-creation-workaround) resolve this issue?

**Comment by AienTech** [comment]
Any updates on this issue?

**Comment by Prince781** [comment]
@AienTech neither the aforementioned branch nor the current master branch of VLS has changed anything when running with WSL?

I've tested VLS with mingw64 and it works. This is what I've guaranteed for VLS's Windows support, but I'll take a look at WSL and see what is happening there.

**Comment by AienTech** [comment]
@Prince781 actually this was an issue in vscode configs. in my case, I set the `G_DEBUG` to `fatal-criticals`, so it caused the error.
For anyone with a similar problem, just open your vscode settings and search for vala, then be sure that you have set the `Vls: Fail on Criticals` to `false`

**Comment by Prince781** [comment]
@aggalex does @AienTech's solution fix your problem?

**Comment by Prince781** [comment]
I will close this seeing as there has been no further activity and the issue appears to be solved. I'll reopen this issue if necessary.
