### ISSUE TITLE
Compile error with vala 0.49 + jsonrpc-glib-1.0.vapi

### ISSUE THREAD

**Issue by yeganaaa** [benwaffle/vala-language-server#144]
Hello
I'm download the latest vala from official gitlab repository and compile it and installed on my system,
vala compiler version is 0.49,
but error occurred while compiling the language server (building with ninja phase),
there is the error message:

```
jsonrpc-glib-1.0.vapi:147.79-147.97: error: Synchronous out-parameters are not supported in async methods
		public async bool call_with_id_async (string method, GLib.Variant? @params, out GLib.Variant id, GLib.Cancellable? cancellable, out GLib.Variant? return_value) throws GLib.Error;
```

I'm very sorry, I know the vala language server uses jsonrpc-glib library and this is not vala-language-server issue,
but I'm wondering that why that error is occur on vapi of jsonrpc-glib came from "apt install libjsonrpc-1.0-dev",
I really have no any idea how to solve it,

thank you

**Comment by Prince781** [comment]
@yeganaaa Vala 0.49 is unstable, while jsonrpc-glib is stable since you installed it from your distro's repository. It's possible this may be a bug. I suggest you install Vala 0.48 (stable). If you're on Ubuntu or Elementary, you can run these commands:

```sh
sudo apt-add-repository ppa:vala-team/next
sudo apt-get remove valac-0.40-vapi "libvala.*-0.40-0"
sudo apt-get install valac-0.48 valac-bin
```

And then you should be good to go.

**Comment by Prince781** [comment]
@yeganaaa Any update on this issue? Did my advice help you?

If there is no update, I will close this issue soon.

**Comment by Prince781** [comment]
I'm closing this issue as there has been no update. Feel free to reopen it.
