### ISSUE TITLE
Renaming doesn't work for lambda arguments

### ISSUE THREAD

**Issue by gavr123456789** [benwaffle/vala-language-server#146]
**Describe the bug**
Renaming doesn't work for lambda arguments

**Software**
OS and version (e.g. Ubuntu 20.04): arch
Code editor (e.g. VSCode): VSCode
Vala Language Server (e.g. git commit, or PPA/AUR version): master
Vala version (`valac --version`): 0.48.9
 

![Peek 2020-09-07 18-49](https://user-images.githubusercontent.com/30507409/92403764-d6a8b800-f13a-11ea-9ec2-b49350003e33.gif)

**Comment by Prince781** [comment]
@gavr123456789 try out the [`issues/146/renaming-doesnt-work-for-lambda-args`](https://github.com/benwaffle/vala-language-server/tree/issue/146/renaming-doesnt-work-for-lambda-args) branch, which should fix your issue
