### ISSUE TITLE
completion does not suggest "class" methods

### ISSUE THREAD

**Issue by aeldemery** [benwaffle/vala-language-server#147]
some of the symbols in gtk4 are not visible for the server, for example:
```c
install_action();
set_layout_manager_type ();
add_bindig_action ();
```
Thanks

**Comment by Prince781** [comment]
I need this information:

1. What version of Vala are you using?
2. How are you using VLS? Did you get it prebuilt from the Ubuntu/Fedora/etc repositories, or did you build it yourself?
3. Are these symbols actually present in `gtk4.vapi`?
4. What is the context you're trying to use these symbols in? Can you provide a code example where you would expect these completion suggestions?

**Comment by aeldemery** [comment]
Thank you for taking the time to look into this issue.

> What version of Vala are you using?
```
vala --version
Vala 0.50.0
```

> How are you using VLS? Did you get it prebuilt from the Ubuntu/Fedora/etc repositories, or did you build it yourself?

I've build it from latest git sources.

>Are these symbols actually present in `gtk4.vapi`?

yes.
for example
```vala
[CCode (cname = "gtk_widget_class_set_layout_manager_type")]
public class void set_layout_manager_type (GLib.Type type);

[CCode (cname = "gtk_widget_class_install_action")]
public class void install_action (string action_name, string? parameter_type, Gtk.WidgetActionActivateFunc activate);

[CCode (cname = "gtk_widget_class_add_binding_action")]
public class void add_binding_action (uint keyval, Gdk.ModifierType mods, string action_name, string format_string, ...);
```

> What is the context you're trying to use these symbols in? Can you provide a code example where you would expect these completion suggestions?

Yes. In this [repo](https://github.com/aeldemery/gtk4_layoutmanager_transformation/blob/42220ca3b34c8f39135face4c2b5758fc63601f7/src/GlobeWidget.vala#L14) I came across those symbols. Please note that the demo in that repo although compiles but don't work yet as it is still work in progress.

**Comment by Prince781** [comment]
@aeldemery 

The syntax for these methods is something I hadn't seen before (`class` type/annotation), but I think I understand it now. These are essentially like static methods with an implicit `this` argument being the class type. So you call them like static methods, and that's why they aren't shown like instance methods.

https://developer.gnome.org/gtk4/stable/GtkWidget.html#gtk-widget-class-install-action

**Comment by Prince781** [comment]
Since these methods are like static methods, they should only show up when you call them like static methods, and so VLS has the right behavior here.

**Comment by aeldemery** [comment]
Thanks for resolving this matter in a way you see right.
If you allow me to express a couple of comments:
1. To tell the truth I don't notice this `class` modifier in the methods signature, although I understand vaguely it's meaning, I couldn't find any documentation in the Vala reference, please see [this link](https://www.vala-project.org/doc/vala/Classes.html#Class_methods).

2. Although not very clear in the c documentation, I have learnt that for example `set_layout_manager_type` don't work unless inside a `static construct` block. The others could be used inside `construct` or class initialization.

3. That some symbols have a special visibility should not prevent the server from identifying the scope and providing the appropriate completion suggestions based on the context.

4. For that reason I think closing the issue as resolved I would consider it as inconvenient.

5. If you could please sacrifice more time looking for how the `vls` could intelligently handle such situations.

Nonetheless thank you very much for your efforts.

**Comment by Prince781** [comment]
> 3. That some symbols have a special visibility should not prevent the server from identifying the scope and providing the appropriate completion suggestions based on the context.

These symbols are static methods, so they should only be called as `Gtk.Widget.[method]()`, and not anything else. I'm not sure I understand the behavior you want.

**Comment by Prince781** [comment]
@aeldemery on review, I see that although these are static methods, they are treated in Vala like instance methods. I understand the problem now.

**Comment by aeldemery** [comment]
Thank you for reconsidering this. We could discuss on irc what is actually the meaning of `class` in this context.

**Comment by Prince781** [comment]
@aeldemery try out the branch for this issue and let me know how it works

**Comment by aeldemery** [comment]
@Prince781 Thank you very much.

I confirm that those functions and the rest of `class` methods like 

```vala
add_shortcut ()
add_binding ()
add_binding_signal ()
add_binding_action ()
set_layout_manager_type ()
set_accessible_role ()
bind_template_child_full ()
...
```

show only inside `static construct` which is equal to `class_init` in `c`, and don't show up inside `construct` or class constructor which is right.

That means that class method look up works as it is supposed to do.

Thank you for your hard work!

**Comment by aeldemery** [comment]
@Prince781 Have you merged this in master? because I switched to master and pulled the latest commits, but it doesn't work anymore?

**Comment by Prince781** [comment]
I changed it to also show class symbols in instance methods, since that's theoretically something that someone might want to do. I was trying to think about how I might support @ricotz's [explicit class-access feature](https://gitlab.gnome.org/GNOME/vala/-/tree/wip/explicit-class-access), but I can leave that for later.
