### ISSUE TITLE
meson backend: use --targets API from meson 0.50.0

### ISSUE THREAD

**Issue by Prince781** [benwaffle/vala-language-server#15]
See https://github.com/mesonbuild/meson/pull/5200
meson 0.50.0 has deprecated `--target-files` in favor of `--targets`. We use `--target-files` in main.vala to get source files for a target. This needs to be changed. This is just a reminder so that when things break later I don't forget why.

**Comment by minkir014** [comment]
Do you know how to fix that?

**Comment by minkir014** [comment]
@Prince781 Are you here?

**Comment by benwaffle** [comment]
@minkir014 the issue description explains how to fix it

**Comment by Prince781** [comment]
Fixed.
