### ISSUE TITLE
Failing on Elementary 6 Preview

### ISSUE THREAD

**Issue by treagod** [benwaffle/vala-language-server#155]
**Describe the bug**
When trying to add the repository via `sudo add-apt-repository ppa:prince781/vala-language-server` I get following error:

```
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 108, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 118, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 613, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 91, in get_sources
    raise NoDistroTemplateException(
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Elementary/next
```

**Software**
Elementary 6 Preview
Vala 0.48.11

**To Reproduce**
Execute `sudo add-apt-repository ppa:prince781/vala-language-server`

**Comment by Prince781** [comment]
Probably because the Ubuntu repo has packages for 18.04 up to 20.04, but eOS next is based off of 20.10 or something later.

**Comment by Prince781** [comment]
This is not really a bug, just an indication that we need to make packages for the next version of Ubuntu and eOS (once they're released). We don't guarantee packages for unreleased/prereleased distros. For now, I would suggest building VLS from source, which has a lot more bug fixes and feature improvements than the packaged VLS anyway right now.
