### ISSUE TITLE
Update README to point to OBS repo for Fedora packages

### ISSUE THREAD

**Issue by overlisted** [benwaffle/vala-language-server#173]
## Describe the bug
`$ sudo dnf copr enable prince781/vala-language-server` returns "Error: This repository does not have any builds yet so you cannot enable it now."

## Software
**OS and version**: Fedora 33
**Vala Language Server**: Not installed
**Vala version**: 0.48.13

## Steps to reproduce the behavior:
1. Install Fedora 33
2. Execute `$ sudo dnf copr enable prince781/vala-language-server` to make VLS installable via DNF
3. Acknowledge that the repo is not controlled by Red Hat
4. See the error

**Comment by Prince781** [comment]
I realize now that I forgot to update the documentation as we're transitioning to using Open Build Service for packaging. I mentioned this in the last [release note](https://github.com/benwaffle/vala-language-server/releases/tag/0.48.1), but I didn't update the README.

If you click [this link](https://software.opensuse.org//download.html?project=home%3APrince781&package=vala-language-server) you can install pre-built VLS for Fedora 32/33/Rawhide or just install the repository to always be up-to-date.

**Comment by overlisted** [comment]
Thank you! The OBS repository works.

**Comment by Prince781** [comment]
Resolved
