### ISSUE TITLE
Segfault when building under Guix

### ISSUE THREAD

**Issue by HiPhish** [benwaffle/vala-language-server#177]
**Describe the bug**
Building with Guix causes a segfault.

**Software**
OS and version: Void Linux
Vala Language Server: 204f8b68cb020539ce0a48adf2430de964b05ab0
Vala version: Vala 0.50.2

**To Reproduce**

1. Check out current master
2. Set up Guix environment `guix environment vala-language server`
3. Follow the build instructions
```
$ meson -Dprefix=$HOME/Desktop/vls build
The Meson build system
Version: 0.53.2
Source dir: /home/hiphish/Applications/lsp/vala-language-server
Build dir: /home/hiphish/Applications/lsp/vala-language-server/build
Build type: native build
Project name: vala-language-server
Project version: 0.48.1
C compiler for the host machine: cc (gcc 10.2.1 "cc (GCC) 10.2.1 20201203")
C linker for the host machine: cc ld.bfd 2.34
Vala compiler for the host machine: valac (valac 0.50.2)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /gnu/store/4spqmyviwbb9kawcf2mrdsiz8ic41k66-profile/bin/pkg-config (0.29.2)
Run-time dependency libvala-0.50 found: YES 0.50.2
Run-time dependency gobject-2.0 found: YES 2.62.6
Run-time dependency jsonrpc-glib-1.0 found: YES 3.33.3
Run-time dependency glib-2.0 found: YES 2.62.6
Run-time dependency gio-2.0 found: YES 2.62.6
Run-time dependency gee-0.8 found: YES 0.20.3
Run-time dependency json-glib-1.0 found: YES 1.4.4
Library posix found: YES
Configuring config.vala using configuration
Run-time dependency gio-unix-2.0 found: YES 2.62.6
Found pkg-config: /gnu/store/4spqmyviwbb9kawcf2mrdsiz8ic41k66-profile/bin/pkg-config (0.29.2)
Found CMake: /usr/bin/cmake (3.19.4)
Build-time dependency scdoc found: NO (tried pkgconfig and cmake)
Program sh found: YES (/gnu/store/4spqmyviwbb9kawcf2mrdsiz8ic41k66-profile/bin/sh)
Program sed found: YES (/gnu/store/4spqmyviwbb9kawcf2mrdsiz8ic41k66-profile/bin/sed)
Program gnome-builder found: NO
plugins/gnome-builder/meson.build:15: WARNING: Assuming version 3.38 for GNOME Builder plugin ABI
Configuring vala_langserv.plugin using configuration
Build targets in project: 2

Found ninja-1.10.0 at /gnu/store/4spqmyviwbb9kawcf2mrdsiz8ic41k66-profile/bin/ninja

$ ninja -C build
ninja: Entering directory `build'
[33/33] Linking target src/vala-language-server.
```
4. Run the executable: `$ ./build/src/vala-language-server`

The server segfaults immediately. Here is what the core dump says when loaded into GDB:

```
$ gdb ./build/src/vala-language-server core.15293
GNU gdb (GDB) 10.1

Reading symbols from ./build/src/vala-language-server...
[New LWP 15293]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/gnu/store/fa6wj5bxkj5ll1d7292a70knmyl7a0cr-glibc-2.31/lib/libthread_db.so.1".
Core was generated by `./build/src/vala-language-server'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f7c5c11ef2c in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0x7ffc30c90f78,
    env=env@entry=0x7ffc30c90f88) at dl-init.c:74
74	dl-init.c: No such file or directory.
```

**Comment by Prince781** [comment]
Could you print the full backtrace?

**Comment by HiPhish** [comment]
I don´t think there is a point to me posting a backtrace here, I have the same issue with other GLib libraries as well if I use Guix to install them. I posted on their mailing list, but no one answered there. I´ll just close this issue here because it´s a more general problem beyond the Vala language server.

**Comment by HiPhish** [comment]
For the sake of completeness, here is the follow-up message I posted on the Guix mailing list with the backtrace (formatting added for GitHub):

> I have tried running the application through GDB to print a backtrace, and here is what it prints:
> 
> ```
> $ gdb ./build/src/vala-language-server
> GNU gdb (GDB) 10.1
> 
> (gdb) run
> Starting program: /home/hiphish/Applications/lsp/vala-language-server/build/
> src/vala-language-server
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/gnu/store/fa6wj5bxkj5ll1d7292a70knmyl7a0cr-
> glibc-2.31/lib/libthread_db.so.1".
> 
> Program received signal SIGSEGV, Segmentation fault.
> 0x00007ffff7fe1f2c in call_init (l=<optimized out>, argc=argc@entry=1, 
> argv=argv@entry=0x7fffffffdd28,
>     env=env@entry=0x7fffffffdd38) at dl-init.c:74
> 74      dl-init.c: No such file or directory.
> 
> (gdb) bt
> #0  0x00007ffff7fe1f2c in call_init (l=<optimized out>, argc=argc@entry=1, 
> argv=argv@entry=0x7fffffffdd28,
>     env=env@entry=0x7fffffffdd38) at dl-init.c:74
> #1  0x00007ffff7fe20a1 in call_init (env=0x7fffffffdd38, argv=0x7fffffffdd28, 
> argc=1, 
> l=<optimized out>) at dl-init.c:37
> #2  _dl_init (main_map=0x7ffff7ffe1a0, argc=1, argv=0x7fffffffdd28, 
> env=0x7fffffffdd38) 
> at dl-init.c:88
> #3  0x00007ffff7fd308a in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
> #4  0x0000000000000001 in ?? ()
> #5  0x00007fffffffe10e in ?? ()
> #6  0x0000000000000000 in ?? ()
> ```
> 
> To me it looks like even before the segmentation fault happens even before the > main function has been called, and it happens in a system library. Is there a dependency I am missing? I still don't understand why the program only crashes if I compile it myself with dependencies from Guix, but not if I install the application itself through Guix.

https://lists.gnu.org/archive/html/help-guix/2021-03/msg00123.html
