### ISSUE TITLE
Cant build on arch

### ISSUE THREAD

**Issue by gavr123456789** [benwaffle/vala-language-server#18]
```> ninja -C build
ninja: Entering directory `build'
[1/9] Compiling Vala source ../main.va.../vala038_workarounds.vala config.vala.
FAILED: vala-language-server@exe/main.c vala-language-server@exe/protocol.c vala-language-server@exe/reporter.c vala-language-server@exe/context.c vala-language-server@exe/iterator.c vala-language-server@exe/vala038_workarounds.c vala-language-server@exe/build/config.c 
valac -C --debug --debug --pkg libvala-0.44 --pkg jsonrpc-glib-1.0 --pkg gee-0.8 --pkg gio-unix-2.0 --pkg gobject-2.0 --pkg glib-2.0 --color=always --directory vala-language-server@exe --basedir ../ --pkg=posix --enable-gobject-tracing ../main.vala ../protocol.vala ../reporter.vala ../context.vala ../iterator.vala ../vala038_workarounds.vala config.vala
../context.vala:45.17-45.38: error: The name `target_glib_major' does not exist in the context of `Vala.CodeContext?'
                _ctx.target_glib_major = 2;
                ^^^^^^^^^^^^^^^^^^^^^^
../context.vala:46.17-46.38: error: The name `target_glib_minor' does not exist in the context of `Vala.CodeContext?'
                _ctx.target_glib_minor = 56;
                ^^^^^^^^^^^^^^^^^^^^^^
../context.vala:47.39-47.60: error: The name `target_glib_minor' does not exist in the context of `Vala.CodeContext?'
                for (int i = 16; i <= _ctx.target_glib_minor; i += 2) {
                                      ^^^^^^^^^^^^^^^^^^^^^^
../main.vala:713.13-713.35: warning: unhandled error `GLib.Error'
            client.reply (id, null);
            ^^^^^^^^^^^^^^^^^^^^^^^
../main.vala:720.13-720.35: warning: unhandled error `GLib.Error'
            client.reply (id, null);
            ^^^^^^^^^^^^^^^^^^^^^^^
../main.vala:752.13-752.35: warning: unhandled error `GLib.Error'
            client.reply (id, null);
            ^^^^^^^^^^^^^^^^^^^^^^^
../main.vala:772.27-784.10: warning: unhandled error `GLib.Error'
../main.vala:772.9-784.11: warning: unhandled error `GLib.Error'
Compilation failed: 3 error(s), 5 warning(s)
ninja: build stopped: subcommand failed.
```

**Comment by gavr123456789** [comment]
Glib 2.60
vala 0.44

**Comment by benwaffle** [comment]
probably because that's a newer version of libvala

**Comment by taozuhong** [comment]
./vala-language-server
** Message: 12:55:35.449: main.vala:117: Finished constructing
** Message: 12:55:45.452: main.vala:67: listening...
** Message: 12:55:55.453: main.vala:67: listening...
** Message: 12:56:05.453: main.vala:67: listening...

according #20 instructions, I have compiled and run it, but it seens not good, ex scan compile_commands.json file and parse all symbols from project and dependency packages.

**Comment by Prince781** [comment]
@taozuhong there are problems with it, but did you try the **wip-completion2** branch?

**Comment by gicmo** [comment]
Not only Arch is affected but now also Fedora 30 (glib 2.60.5).

**Comment by Prince781** [comment]
Is this still a problem?

**Comment by gavr123456789** [comment]
That's the first thing I see after pressing F5  (Last step in instruction)
![image](https://user-images.githubusercontent.com/30507409/62622031-0547d400-b926-11e9-92d6-930d67517c4e.png)  
And this after clicking show errors:
![image](https://user-images.githubusercontent.com/30507409/62622110-4344f800-b926-11e9-83a7-51ce480b8d31.png)  
  
ЗЫ There misprint "cd vala-lanugage-server" -> language

**Comment by Prince781** [comment]
@gavr123456789 It looks like it builds successfully.

**Comment by Prince781** [comment]
As to the issue with the vscode plugin, I think either @benwaffle or @thiagoabreu would be better-suited to address.

**Comment by benwaffle** [comment]
Can you try with the latest version of vala-code?
```
$ git pull
$ npm install
$ npm run compile
```

**Comment by gavr123456789** [comment]
@benwaffle  
```zsh
┌ ~/Documents/builds/vala-code
└> % npm install                                          (master|+1) 19:34:35
audited 8 packages in 0.457s
found 0 vulnerabilities

┌ ~/Documents/builds/vala-code
└> % npm run compile                                      (master|+1) 19:34:43

> vala@0.3.2 compile /home/gavr/Documents/builds/vala-code
> tsc -p ./
```
hmm, Everything went fine, now after pressing F5 there are no errors appear. Another VS Code opens in which no new extensions are installed, but there is support for Vala syntax if you create a new `.vala` file in it. But there is no code diagnostics, it looks like I just install the Vala-Code plugin from the Extensions menu.

**Comment by benwaffle** [comment]
If you go to the Log and go to `vala-language-server` you should see stuff.

**Comment by gavr123456789** [comment]
Here for the listening, but not the file that I editing right now (at least not the same as the name and line number)  
![image](https://user-images.githubusercontent.com/30507409/62799426-72579700-bae9-11e9-999f-e60d17a2df11.png)

**Comment by benwaffle** [comment]
Currently we only work with meson projects.

**Comment by gavr123456789** [comment]
Oh, it's just a line of code from where this log is written, huh. In any case, nothing happens here except endless lines of `listening`

**Comment by gavr123456789** [comment]
okey, so i can check it only on proj with meson, will try in hour later, going to get the chicken from kfc now xd

**Comment by Prince781** [comment]
I'm seeing this same issue when I try to open VLS from the vscode extension.

**Comment by benwaffle** [comment]
which issue? you can't just open a single vala file. you need a meson project.

**Comment by Prince781** [comment]
Just a bunch of "listening..." messages. No response when I modify the document.

**Comment by benwaffle** [comment]
i think that's expected

**Comment by Prince781** [comment]
There are no diagnostics shown when I type.

**Comment by Prince781** [comment]
I've partially reverted 3f2cae0667d3a591e4b8b7eddefb986ecbeca7b2, which fixes the issue. I guess it's probably because of the environment variables I was using. Nevertheless, I'm keeping this change since it should prevent all surprises in the future.

**Comment by gavr123456789** [comment]
So I tried to open a project with meson(generated Builder) and now I'm really getting some messages (here I specifically skipped `;` ) However visually nothing happens and I don't understand I expect I'll get something like a missing semicolon, however here I see 
```shell
vls: mail.vala:121: Got notification! text Document/didChange
vls: context.vala:22: dirty context, rebuilding
vlc: vlc_break_symbol_rfs: assertion 'sym != NULL' failed
```
![image](https://user-images.githubusercontent.com/30507409/62835808-2cbfd900-bc65-11e9-8bd8-08b8586a0320.png)

**Comment by benwaffle** [comment]
Looks like a bug. @Prince781 maybe the vala038_workarounds need to be updated?

**Comment by Prince781** [comment]
@gavr123456789 Did you try with the latest version of master? In this recent commit (https://github.com/benwaffle/vala-language-server/commit/e4dcfb3fda8b8c61daa83d9266014da5a280b747) I changed things so that any non-JSON-RPC messages will get sent to stderr, which should allow things to still work when VLS encounters one of these situations.

**Comment by gavr123456789** [comment]
no, will try again today

**Comment by Prince781** [comment]
@gavr123456789 well?

**Comment by gavr123456789** [comment]
@Prince781  sorry for waiting, now i have no libvala to build vala-language-server, and i cant find it on arch packages.  
![image](https://user-images.githubusercontent.com/30507409/63115668-5ac45680-bfa0-11e9-88be-18e9d6580432.png)

**Comment by Prince781** [comment]
@gavr123456789 that doesn't look like VLS you're building. We don't depend on cmake, and we depend on libvala-0.44

I'm on arch and have no problems building VLS. Are your repos broken? https://www.archlinux.org/packages/extra/x86_64/vala/

**Comment by gavr123456789** [comment]
@Prince781 hmm okey, what im doing wrong? https://youtu.be/goWrJc2DVxk

**Comment by benwaffle** [comment]
Our fault. Try `git submodule update` in `vala-code` and then building VLS

**Comment by gavr123456789** [comment]
Nice! now all works, so edit README for others peples https://youtu.be/CqSdrDNYPTg . I don't know anything about the VS Code extensions architecture, how do I make this extension stay enabled forever?

**Comment by gavr123456789** [comment]
Peek Definition and Go To Definition works great!

**Comment by gavr123456789** [comment]
It cant find Gee lib, even if i add meson file with its as dependency  
![image](https://user-images.githubusercontent.com/30507409/63201350-8bce8500-c08d-11e9-8cd6-0792d688ddf5.png)

**Comment by Prince781** [comment]
@gavr123456789 I think you currently must manually regenerate the build directory when you change the meson.build file. This means either deleting the temporary build directory that VLS created if there was no build directory, or if there was, running `meson build` again.

**Comment by gavr123456789** [comment]
@Prince781  all good now, idk why. Last question, how to install it in right way?

**Comment by Prince781** [comment]
`ninja -C build install` will install into `/usr/local`

If you want to change the prefix, then do `meson -Dprefix=<prefix> build` before.
