### ISSUE TITLE
Cant build on elementary

### ISSUE THREAD

**Issue by gavr123456789** [benwaffle/vala-language-server#19]
`Dependency libvala-0.42 found: NO (tried pkgconfig and cmake)`
there are 0.40 ^^

**Comment by gavr123456789** [comment]
all works with manually fix meson

**Comment by benwaffle** [comment]
That's weird, our meson.build automatically detects your version of vala. (https://github.com/benwaffle/vala-language-server/blob/master/meson.build#L3-L6). It didn't work?

**Comment by gavr123456789** [comment]
i just dont know what it was, all works fine now  
but i cant use it anyway https://github.com/thiagoabreu/vala-code/issues/14

**Comment by benwaffle** [comment]
I have an updated fork, https://github.com/benwaffle/vala-code

**Comment by gavr123456789** [comment]
Amm, it just happened again, thats proof (not on ur new fork) https://youtu.be/do7R3LSUu5I

**Comment by gavr123456789** [comment]
just tried this new [repo](https://github.com/benwaffle/vala-code), and I have absolutely the same situation as in the video above.

**Comment by benwaffle** [comment]
run `git checkout master` in `vala-language-server/`. Then you can try `meson build`.

**Comment by benwaffle** [comment]
@gavr123456789 it works here on macOS. I've updated the dependencies on vala-code, so run `git pull` and see if that fixes it for you.

What version of nodejs and VSCode are you running?

**Comment by gavr123456789** [comment]
@benwaffle  now vala version detection works, but after F5 still same effect, 3 problems with namespace vscode. 
vs code about 
![image](https://user-images.githubusercontent.com/30507409/57923366-c536ff00-78aa-11e9-8f48-a31961cc152b.png)

**Comment by benwaffle** [comment]
did you run `npm install` again to update the vscode language client?

**Comment by gavr123456789** [comment]
thank you for trying to solve my problem so long. ye, every time i clone all repo from zero. the best way for you to make sure I'm doing everything right is to try it out on the vm. By the way, if you're on a mac, why are you using vala instead of swift?
