### ISSUE TITLE
completion

### ISSUE THREAD

**Issue by Prince781** [benwaffle/vala-language-server#23]
`wip-completion2` is a mess. I think I want to delete it and start over.
The major problem with completion is that it only works if the document is syntactically valid, because semantic analysis never proceeds after syntax errors. Two ways of approaching this:

1. Cache semantic info and try to guess the current symbol under the cursor with some parsing.
2. Change `valac` to support semantic analysis after syntax errors.

**Comment by Prince781** [comment]
I notice that document symbol outlining still works with syntax errors, which implies that maybe since last time `valac` has been changed and (2) is taken care of. I'll investigate later.

**Comment by benwaffle** [comment]
@ricotz How much does libvala handle parsing and semantic analysis with syntax errors?

I thought it would fail at the parsing step.

**Comment by ricotz** [comment]
@benwaffle You already have the control whether to abort or not. Under which conditions you are invoking the `parser.parse(context)` followed by `context.check()` is your responsibility. Although running the `SemanticAnalyser` on a broken syntax-tree will create issues.

Error reporting in the parser is essential, but it might be possible to have a less broken syntax-tree. This would require changes in the parser.
