### ISSUE TITLE
Good Outlining Support

### ISSUE THREAD

**Issue by minkir014** [benwaffle/vala-language-server#25]
We need to add support for good viewing outline symbols.

**Comment by Prince781** [comment]
Okay, I think I can say we now have this feature.

**Comment by Prince781** [comment]
The only thing left on the agenda is to get namespaces working. This is a bit tricky because namespace symbols can appear many times when visiting, particularly if you have something like:

```Vala
class Ns.Class1{ /* ... */ }
class Ns.Class2 { /* ... */ }
```

**Comment by benwaffle** [comment]
Can we make the symbols ordered in the same order as they are defined in the code?

**Comment by Prince781** [comment]
> Can we make the symbols ordered in the same order as they are defined in the code?

Why would you want that? Not having the symbols sorted kind of defeats the purpose of the outline—to help you find symbols in your code.

**Comment by Prince781** [comment]
> Can we make the symbols ordered in the same order as they are defined in the code?

Also, this is the behavior for LSP clients that don't support hierarchical symbol outlining, like vim-lsp and gnome-builder.

**Comment by Prince781** [comment]
This issue is fixed in #39
