### ISSUE TITLE
play nice with VSCode meson plugin

### ISSUE THREAD

**Issue by benwaffle** [benwaffle/vala-language-server#29]
maybe it can handle configuring the build dir for us? or we just copy the logic https://github.com/asabil/vscode-meson/tree/master/src/meson

**Comment by Prince781** [comment]
I don't know whether we should close this issue because of better Meson support in VLS now, and also because we are now working on a protocol for clients to send configuration to VLS.

**Comment by benwaffle** [comment]
VLS doesn't interact at all with the meson plugin. Need to do research into what's possible

**Comment by Prince781** [comment]
But does it matter? Seems like the point is moot now that we support Meson in VLS.

**Comment by benwaffle** [comment]
I was hoping we could at least share build dirs with the meson plugin, and maybe offload some of the work

**Comment by Prince781** [comment]
Well that's no longer an issue since Meson support has been improved. I think it's better to have this in VLS for now, since we can recognize Meson projects regardless of whatever client is being used.

I think this issue should be closed.

**Comment by benwaffle** [comment]
This issue title isn't "meson support". I'm trying to see if we can make vscode closer to an IDE like Builder where different plugins talk to each other

**Comment by Prince781** [comment]
No I understand, but I still think that's out of scope for a language server. What is more in scope would be discussing a general way for any plugin to interact with VLS.
