### ISSUE TITLE
A shorter name for the server

### ISSUE THREAD

**Issue by Prince781** [benwaffle/vala-language-server#30]
I'm not proposing to change the name of the project, just the executable. I feel `valals` would be better. It's short and still unambiguous, unlike `vls`.

**Comment by benwaffle** [comment]
why?

**Comment by Prince781** [comment]
I think it's too long.

**Comment by benwaffle** [comment]
yeah, but when are you typing it?

**Comment by Prince781** [comment]
> yeah, but when are you typing it?

Not ever, really. But I still think it's a clunky name. A lot of other server names are pretty short (`clangd`, `glslls`, `pyls`).

idk

On the other, there are other servers that have a long name too (`bash-language-server`).

**Comment by benwaffle** [comment]
`valals` makes me think of `ls`. I think `vala-language-server` is fine. It's unambiguous and it's not like anyone has to type it.

**Comment by Prince781** [comment]
What about `valad`?

**Comment by benwaffle** [comment]
nah, there's nothing wrong with the current name.

**Comment by benwaffle** [comment]
`valad` doesn't say what the daemon does

**Comment by Prince781** [comment]
Okay, fair enough. I'll drop this issue.
