### ISSUE TITLE
go to definition is broken under certain invalid files

### ISSUE THREAD

**Issue by benwaffle** [benwaffle/vala-language-server#34]
We're narrowing the nodes down to the `Expression` but I think the `symbol_reference` is null so we don't find the definition.

**Comment by Prince781** [comment]
Could this commit (57abbeab) have broken it? It fixed some other things, though.

**Comment by Prince781** [comment]
I've noticed the same thing when trying to get definitions from MemberAccess nodes. See the chat (gitter.im)

**Comment by benwaffle** [comment]
You can reproduce by deleting a `;`

**Comment by Prince781** [comment]
I think this has been largely fixed in #39
