### ISSUE TITLE
Can't build on windows due to Posix namespace

### ISSUE THREAD

**Issue by taozuhong** [benwaffle/vala-language-server#35]
I have tried to build it on windows via MSYS2, but it failed, due to rely on Posix namespace.

**Comment by benwaffle** [comment]
```vala
» rg Posix
main.vala
97:        var new_stdout_fd = Posix.dup(Posix.STDOUT_FILENO);
98:        Posix.close(Posix.STDOUT_FILENO);
99:        Posix.dup2(Posix.STDERR_FILENO, Posix.STDOUT_FILENO);
101:        var stdin = new UnixInputStream (Posix.STDIN_FILENO, false);
106:            if (!Unix.set_fd_nonblocking (Posix.STDIN_FILENO, true)
```

**Comment by Prince781** [comment]
Not familiar with MSYS2, but shouldn't there be a POSIX layer for Windows?

**Comment by taozuhong** [comment]
https://github.com/msys2/MSYS2-packages/issues/1692
===> MINGW glib2 never has gio-unix component

**Comment by Prince781** [comment]
>MINGW glib2 never has gio-unix component

Then I guess that means VLS doesn't work on MINGW.

**Comment by taozuhong** [comment]
Don't worry about it, there are an better environment for VLS： WSL2.

**Comment by Prince781** [comment]
This is technically more of an enhancement than a bug—we don't support Windows and have no immediate plans to.

**Comment by gavr123456789** [comment]
@taozuhong If you still haven't found[ it](https://github.com/philippejer/vala-language-server-alpha), this is fork of this VLS that [works ](https://github.com/philippejer/vala-language-server-alpha/issues/8)on Windows.

**Comment by taozuhong** [comment]
> @taozuhong If you still haven't found[ it](https://github.com/philippejer/vala-language-server-alpha), this is fork of this VLS that [works ](https://github.com/philippejer/vala-language-server-alpha/issues/8)on Windows.

Got it, tried it already, it seems response slowly, so I turn back Vala Code extension now.

**Comment by Prince781** [comment]
@taozuhong I've made changes to allow VLS to build on Windows. If you can, let me know whether it works in VSCode.

**Comment by taozuhong** [comment]
> @taozuhong I've made changes to allow VLS to build on Windows. If you can, let me know whether it works in VSCode.

I've tested the source code on MSYS2 environment, compiled and started to run successfully.

**Comment by Prince781** [comment]
@taozuhong So we can close this issue?

**Comment by taozuhong** [comment]
Sure and done.
