### ISSUE TITLE
Just news

### ISSUE THREAD

**Issue by gavr123456789** [benwaffle/vala-language-server#36]
Looks like autocompletion works fine in GVLs (there gif in [this](https://github.com/elementary/code/pull/599) thread) but there no plugin for vs code yet.

**Comment by Prince781** [comment]
We're aware. GVLS doesn't support LSP the last time I checked, so it's a lot less versatile.

**Comment by Prince781** [comment]
I've added a room [here](https://gitter.im/vala-language-server/community) for general discussion. Since this is not an issue, I'm closing this.

**Comment by benwaffle** [comment]
@Prince781 the description for GVLS says "GNOME Vala Language Server is a library designed to provide services for IED using Vala as programming language."

**Comment by benwaffle** [comment]
it definitely supports LSP https://gitlab.gnome.org/esodan/gvls/blob/master/src/gvls-server-lsp.vala#L37-43

**Comment by Prince781** [comment]
@benwaffle  interesting. Do you think we could use this in any way?
