### ISSUE TITLE
Add support for "using" keyword

### ISSUE THREAD

**Issue by jtrees** [benwaffle/vala-language-server#42]
Currently the `using` keyword doesn't seem to be supported.

#### Example

```vala
# File 1
public class Foo.Bar {
    // ...
}

# File 2
using Foo;

public class Example {
    public Bar get_bar () { return new Bar (); }
}
```

This will yield an error at `public Bar get_bar ()` because `Bar` cannot be found.

**Comment by Prince781** [comment]
Is this still an issue?

**Comment by Prince781** [comment]
I've tried this scenario with the current version of VLS and libvala-0.48 and it works. I'm closing this issue for now unless it's still a problem.
