### ISSUE TITLE
VS Code: LSP Client connect to  GVls Server

### ISSUE THREAD

**Issue by esodan** [benwaffle/vala-language-server#43]
A new 0.12 release of [GVls](https://gitlab.gnome.org/esodan/gvls) is out, it provides the foundations to implement Clients for many IED like VS Code, just need to find a way to connect this project's client to [GVls](https://gitlab.gnome.org/esodan/gvls) server.

[GVls](https://gitlab.gnome.org/esodan/gvls) provides TCP/IP local connection using 1024 port or STDIO.
A way to run the server from VS Code and connect to it is required.

**Comment by Prince781** [comment]
Thanks for your hard work. I will take a look at some of your code and see if and how we could collaborate on features.
