### ISSUE TITLE
Target Vala LTS

### ISSUE THREAD

**Issue by benwaffle** [benwaffle/vala-language-server#47]
Next LTS version will be 0.48

elementary OS 6 will launch with that

Let's maintain compatibility for 0.48, even as new versions are released

**Comment by Prince781** [comment]
A good idea, but it means I'll have to get all of my patches approved soon.

**Comment by Prince781** [comment]
It looks like the code freeze has passed and so we might not have the upstream changes for 0.48

**Comment by Prince781** [comment]
It looks like @ricotz cherry-picked six or so commits from the LSP work, but a lot of the important stuff for signatureHelp and member access completion has yet to be merged. I suspect that at least some commits (like the work for `signatureHelp`) may not make it as they introduce API changes.

**Comment by Prince781** [comment]
I think we can close this issue since we do support Vala LTS now.
