### ISSUE TITLE
List tasks for newcomers

### ISSUE THREAD

**Issue by Prince781** [benwaffle/vala-language-server#48]
There are a couple of tasks/bugs we could single out as newcomer projects that would help more people get involved in development of VLS.

**Comment by giacomoalbe** [comment]
Hi @Prince781!

This will definitely help me get started with VLS development, since I would truly like to have it working, it would be more than necessary to my workflow!

Is there anything I can tackle which is also _beginner friendly_ from a language server point of view?

**Comment by Prince781** [comment]
@giacomoalbe see the [newcomers](https://github.com/benwaffle/vala-language-server/labels/newcomers) label
