### ISSUE TITLE
Use gvs library instead of object_to_variant/parse_variant

### ISSUE THREAD

**Issue by Prince781** [benwaffle/vala-language-server#49]
we should look into using [this obscure library](https://github.com/tcbrindle/gvs) for converting GObjects to GVariants rather than using the object <-> JSON <s>string</s> <-> variant pipeline we have with `object_to_variant` / `parse_variant`

**Comment by benwaffle** [comment]
I don't believe it's object -> string -> variant, it's object -> Json.Node -> variant

**Comment by benwaffle** [comment]
And let's wait until variant serialization is a performance bottleneck before we do this.

**Comment by Prince781** [comment]
You're right about it being Json.Node instead of string. And you're also right that we should determine whether this is a performance bottleneck before doing anything about it. I suppose I'll let this issue serve to remind me of the existence of this repo.

**Comment by Prince781** [comment]
I think this issue hasn't been shown to be relevant. I'll close it.
