### ISSUE TITLE
manpage

### ISSUE THREAD

**Issue by Prince781** [benwaffle/vala-language-server#63]
Create manpage for VLS

**Comment by Cogitri** [comment]
What should be documented on the manpage? AFAICT vls doesn't accept any parameters, or does it?

**Comment by Prince781** [comment]
@Cogitri yeah, I intend for VLS to have some configuration from the command-line in the future (for example, if socket communication is implemented). I think a manpage at present would be pretty bare, but it might include some info about using `G_MESSAGES_DEBUG=all`, for example.
