### ISSUE TITLE
create distro packages

### ISSUE THREAD

**Issue by Prince781** [benwaffle/vala-language-server#64]
- [x] Archlinux (done - https://aur.archlinux.org/packages/vala-language-server/, https://aur.archlinux.org/packages/vala-language-server-git/)
- [x] Ubuntu 18.04 (done - https://launchpad.net/~prince781/+archive/ubuntu/vala-language-server)
- [x] Fedora 32 (done - https://copr.fedorainfracloud.org/coprs/prince781/vala-language-server/)

**Comment by benwaffle** [comment]
where is the script to build a deb?

**Comment by Prince781** [comment]
@benwaffle see `wip/packaging/debian`

You basically do this:

1. update `debian/changelog` appropriately if the version changes. The changelog is in a special format that the Debian build system will use to generate the package.
2. update `debian/control` with package dependencies if they change
3. Build a *source* package with the command `debuild -uc -us -S`
4. In the parent directory (outside of VLS) you'll see the packages and the `.changes` file. Run `debsign -k <your private GPG key you used for the PPA> <file>.changes`
5. Run `dput <file>.changes` to upload to the PPA
6. The binary version(s) of the packages (the one(s) you install) will be automatically built online

**Comment by Cogitri** [comment]
FWIW it was added to Alpine Linux: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/6696
