### ISSUE TITLE
crash on macOS 10.15.3

### ISSUE THREAD

**Issue by benwaffle** [benwaffle/vala-language-server#80]
**Describe the bug**
Is this enough info?
```
(process:4392): GLib-GObject-WARNING **: 22:37:22.696: cannot register existing type 'JsonParser'

(process:4392): GLib-GObject-WARNING **: 22:37:22.696: cannot add private field to invalid (non-instantiatable) type '<invalid>'

(process:4392): GLib-CRITICAL **: 22:37:22.696: g_once_init_leave: assertion 'result != 0' failed

(process:4392): GLib-GObject-CRITICAL **: 22:37:22.696: g_object_new_valist: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
```

**Software**
OS and version (e.g. Ubuntu 20.04): macOS 10.15.3
Code editor (e.g. VSCode): VScode
Vala Language Server (e.g. git commit, or PPA/AUR version): 46efbd6d431378ef7c0591df66729cd0770a4437
Vala version (`valac --version`): 0.48.2

**To Reproduce**
Source code repo: https://github.com/benwaffle/vala-gen-json

1. Open the project
2. Nothing works

**Comment by Prince781** [comment]
@benwaffle what do you see if you just run vala-language-server from the terminal?

**Comment by benwaffle** [comment]
It does not have this error

**Comment by Prince781** [comment]
@benwaffle is this the first error you see? Is it possible there's something wrong with your json-glib installation?

**Comment by benwaffle** [comment]
possibly

**Comment by Prince781** [comment]
@benwaffle I've tried VLS master on both Windows and Linux and it works. I don't have access to a Mac, so I think it would be easier for you to figure out what's going wrong, unless you discover an issue with code I've written.

So I'm assigning this issue back to you, for now.

**Comment by Prince781** [comment]
@benwaffle status? Is this still an issue?
