### ISSUE TITLE
Error messages upon SIGTERM

### ISSUE THREAD

**Issue by Cogitri** [benwaffle/vala-language-server#90]
**Describe the bug**
When sending SIGTERM to v-l-s it throws errors when quitting:

```
vala-language-server
vls-DEBUG: main.vala:223: Finished constructing
vls-DEBUG: main.vala:2412: shutting down...

(process:30965): GLib-GObject-WARNING **: 14:04:19.952: invalid (NULL) pointer instance

(process:30965): GLib-GObject-CRITICAL **: 14:04:19.952: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
```

**Software**
OS and version (e.g. Ubuntu 20.04): Alpine Linux Edge
Code editor (e.g. VSCode):
Vala Language Server (e.g. git commit, or PPA/AUR version): 0.48.0-alpha3
Vala version (`valac --version`): 0.48.3

**To Reproduce**

1. $ vala-language-server
2. $ killlall vala-language-server

**Comment by Prince781** [comment]
Fixed. Thanks for your report.
