### ISSUE TITLE
CodeContext profile not set

### ISSUE THREAD

**Issue by LinArcX** [benwaffle/vala-language-server#92]
**Describe the bug**
I just can see error messages in neovim when i type something [wrong](https://gist.githubusercontent.com/LinArcX/c8e9bc4eec041116639293abb011a9b0/raw/6a0f961a6cec682c5fe163a3148e1cc1a1967c60/Screenshot%2520from%25202020-04-12%252018-05-56.png). None of normal features of a language server like code-completion , jump to definition, .. don't work.

**Software**
OS and version (e.g. Ubuntu 20.04): void-linux
Code editor (e.g. VSCode): neovim-0.4.3_1 
Vala Language Server (e.g. git commit, or PPA/AUR version): v0.48-alpha3 (built directly on my machine)
Vala version (`valac --version`):0.48.3

**To Reproduce**

1. Install neovim + coc.nvim and follow [this issue](https://github.com/neoclide/coc.nvim/issues/1746).
2. compile VLS from source.
3. Start editing a `.vala` file.

**Comment by Prince781** [comment]
Wait, you built VLS with Vala 0.46? Also, did you try rebuilding after running git revert 877f6cf9d4dc38f85f981a3a902b8bd118fd38dd ?

**Comment by LinArcX** [comment]
Sorry. My bad. Actually in void-repo it's [0.46.3](https://github.com/void-linux/void-packages/blob/73f8796d89b126ed096ea38dbd5d6ec3d31e496f/srcpkgs/vala/template#L4)
But i changed the version number(to 0.48.3) and compiled it again from source.

**Comment by Prince781** [comment]
@LinArcX can you try out the `bug/set-codecontext-profile` branch and see if it works for you now?

**Comment by Prince781** [comment]
@LinArcX also, if this is your project: https://github.com/LinArcX/wingpanel-disk-usage, then since it has no `meson.build` file, it cannot determine what packages you're using. So you should still see errors with `Gtk` being undefined.

**Comment by LinArcX** [comment]
[Seems better.](https://gist.githubusercontent.com/LinArcX/c8e9bc4eec041116639293abb011a9b0/raw/4c0fa5f76f7210d0965273196f05ffab9cf99db4/Screenshot%2520from%25202020-04-13%252009-36-26.png)

**Comment by Prince781** [comment]
@LinArcX yup, it looks like it's working now.

Now, keep in mind that completion support is still a work in progress (https://github.com/benwaffle/vala-language-server/issues/71), and there's currently a branch (https://github.com/benwaffle/vala-language-server/pull/82) that should be merged soon to address it.
