### ISSUE TITLE
active parameter support in signature help

### ISSUE THREAD

**Issue by gavr123456789** [benwaffle/vala-language-server#99]
**Software**
OS and version (e.g. Ubuntu 20.04):
Code editor : VSCode
Vala Language Server : 0.48 alpha
Vala version : 0.48.3

**To Reproduce**
1. Start write arguments for function

![изображение](https://user-images.githubusercontent.com/30507409/79678520-195a0a00-8205-11ea-80dc-f2b5323d9079.png)

**Comment by Prince781** [comment]
"Active parameter" requires pending changes made in the upstream parser. See the README about this issue.

**Comment by Prince781** [comment]
It's possible I could come up with a hack for this in the mean time, but it won't always be accurate.

**Comment by Prince781** [comment]
Implemented in 72beba0
